apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}-controlplane-config
  namespace: {{ .Values.namespace }}
data:
  EDC_PARTICIPANT_ID: {{ .Values.participantId | quote }}
  EDC_IAM_ISSUER_ID: {{ .Values.participantId | quote }}
  EDC_IAM_DID_WEB_USE_HTTPS: "false"
  WEB_HTTP_PORT: "{{ .Values.controlplane.ports.web }}"
  WEB_HTTP_PATH: "/api"
  WEB_HTTP_MANAGEMENT_PORT: "{{ .Values.controlplane.ports.management }}"
  WEB_HTTP_MANAGEMENT_PATH: "/api/management"
  WEB_HTTP_MANAGEMENT_AUTH_TYPE: "tokenbased"
  WEB_HTTP_MANAGEMENT_AUTH_KEY: "password"
  WEB_HTTP_CONTROL_PORT: "{{ .Values.controlplane.ports.control }}"
  WEB_HTTP_CONTROL_PATH: "/api/control"
  WEB_HTTP_PROTOCOL_PORT: "{{ .Values.controlplane.ports.protocol }}"
  WEB_HTTP_PROTOCOL_PATH: "/api/dsp"
  WEB_HTTP_CATALOG_PORT: "{{ .Values.controlplane.ports.catalog }}"
  WEB_HTTP_CATALOG_PATH: "/api/catalog"
  WEB_HTTP_CATALOG_AUTH_TYPE: "tokenbased"
  WEB_HTTP_CATALOG_AUTH_KEY: "password"
  EDC_DSP_CALLBACK_ADDRESS: "http://{{ include "connector.fullname" . }}-controlplane:{{ .Values.controlplane.ports.protocol }}/api/dsp"
  EDC_VAULT_HASHICORP_URL: {{ .Values.vault.url | quote }}
  EDC_VAULT_HASHICORP_TOKEN: {{ .Values.vault.token | quote }}
  EDC_MVD_PARTICIPANTS_LIST_FILE: "/etc/participants/participants.json"
  EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: "10"
  EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: "10"
  EDC_DATASOURCE_DEFAULT_URL: {{ .Values.jdbc.url | quote }}
  EDC_DATASOURCE_DEFAULT_USER: {{ .Values.jdbc.user | quote }}
  EDC_DATASOURCE_DEFAULT_PASSWORD: {{ .Values.jdbc.password | quote }}
  EDC_SQL_SCHEMA_AUTOCREATE: "true"
  EDC_IAM_STS_OAUTH_TOKEN_URL: {{ .Values.stsTokenUrl | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_ID: {{ .Values.participantId | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: "{{ .Values.participantId }}-sts-client-secret"
  JAVA_TOOL_OPTIONS: "{{ ternary "-XX:UseSVE=0" "" .Values.useSVE }}-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address={{ .Values.controlplane.ports.debug }}"
