apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}-dataplane-config
  namespace: {{ .Values.namespace }}
data:
  EDC_HOSTNAME: {{ include "connector.fullname" . }}-dataplane
  EDC_RUNTIME_ID: {{ include "connector.fullname" . }}-dataplane
  EDC_PARTICIPANT_ID: {{ .Values.participantId | quote }}
  EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: "{{ .Values.participantId }}#key-1"
  EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: "{{ .Values.participantId }}#key-1"
  EDC_DPF_SELECTOR_URL: "http://{{ include "connector.fullname" . }}-controlplane:{{ .Values.controlplane.ports.control }}/api/control/v1/dataplanes"
  WEB_HTTP_PORT: "{{ .Values.dataplane.ports.web }}"
  WEB_HTTP_PATH: "/api"
  WEB_HTTP_CONTROL_PORT: "{{ .Values.dataplane.ports.control }}"
  WEB_HTTP_CONTROL_PATH: "/api/control"
  WEB_HTTP_PUBLIC_PORT: "{{ .Values.dataplane.ports.public }}"
  WEB_HTTP_PUBLIC_PATH: "/api/public"
  EDC_VAULT_HASHICORP_URL: {{ .Values.vault.url | quote }}
  EDC_VAULT_HASHICORP_TOKEN: {{ .Values.vault.token | quote }}
  JAVA_TOOL_OPTIONS: "{{ ternary "-XX:UseSVE=0" "" .Values.useSVE }}-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address={{ .Values.dataplane.ports.debug }}"
  EDC_DATASOURCE_DEFAULT_URL: {{ .Values.jdbc.url | quote }}
  EDC_DATASOURCE_DEFAULT_USER: {{ .Values.jdbc.user | quote }}
  EDC_DATASOURCE_DEFAULT_PASSWORD: {{ .Values.jdbc.password | quote }}
  EDC_SQL_SCHEMA_AUTOCREATE: "true"
  EDC_IAM_STS_OAUTH_TOKEN_URL: {{ .Values.stsTokenUrl | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_ID: {{ .Values.participantId | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: "{{ .Values.participantId }}-sts-client-secret"
