apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . }}-dataplane
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "connector.fullname" . }}-dataplane
  ports:
    - name: control
      port: {{ .Values.dataplane.ports.control }}
    - name: public
      port: {{ .Values.dataplane.ports.public }}
