apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}-participants
  namespace: {{ .Values.namespace }}
data:
  participants.json: |
{{ toJson .Values.participantsList | indent 4 }}
